Hecter94/EndlessSky-PluginArchive

Plugin Manifest.md

This should be the names of all of the plugins in the archive, unless I missed some. If new plugins get added, they should be able to be added here pretty easily.

DJF113 description update

---

Plugin Manifest.md

Mostly focused on attribution to plugins pulled from google group

Manifest Update

---

Plugin Manifest.md

I went through and added the recently added mods to the manifest.

Add mods to manifest

---

Plugin Manifest.md

Add a bunch more + a few corrections/fix

Update Plugin Manifest.md

---

Plugin Manifest.md

Androids plugin was in twice, so I removed one. Also added a few more descriptions and icons, and fixed the Twin Argosy icon.

Djf113 patch 1

---

Working/All Plugins/Ursa Polaris/data/UPMissions.txt
Working/All Plugins/Ursa Polaris/data/UPShips.txt
Working/Cheats/Ursa Polaris/data/UPMissions.txt
Working/Cheats/Ursa Polaris/data/UPShips.txt

Fixing what shows up in the error log, haven't checked the mission chain yet.

UP error fixes

---

Working/All Plugins/Endless Romances/about.txt
Working/All Plugins/Endless Romances/data/missions/taely.txt
Working/Story/Endless Romances/about.txt
Working/Story/Endless Romances/data/missions/taely.txt

by X_Ray123456#5822 on Discord

Add Endless Romance

---

res/pluginlist/Mega Freight.txt

Test adding direct link to Mega Freight download.

Update Mega Freight direct link.

---

res/pluginlist/Kraz Expanded.txt

Added the txt for
https://github.com/Oskatel/Kraz-Expanded

new plugin 'Kraz Expanded'

---

res/pluginlist/Ruin the Fun.txt

I could not find a required format for the `status` field, so feel free to adapt it.

Update Ruin the Fun status

---

res/pluginlist/additional.command.buttons.txt
res/pluginlist/automata.destruction.0percent.txt
res/pluginlist/automata.destruction.23percent.txt
res/pluginlist/automata.destruction.51percent.txt
res/pluginlist/automata.destruction.75percent.txt
res/pluginlist/automata.in.human.space.txt
res/pluginlist/galactic.capital.investment.txt
res/pluginlist/kor.efret.shipyard.txt
res/pluginlist/more.boarding.missions.txt
res/pluginlist/snowfeather.robotics.txt
res/pluginlist/too.many.asteroids.txt
res/pluginlist/unique.fix.txt

for better reflecting actual and future updates.

changed descriptions of my plugins

---

.github/workflows/manual_check_updates_readme.yml
res/src/checkdirectlinks.py
res/src/makemd.py

New workflow
Same as the daily automatic, but manually started
Checkdirectlinks.py 
Added try command on last unchecked link handling when the zip should get downloaded, which somehow failed today.
Makemd.py
Added 10 minutes wait time to prevent that on purpose failing, cause the release zips cant be reached. 
Tested that just for 2 days, so not sure if it works reliable.

Error handling improvements

---

res/pluginlist/Old Memory.txt

Adding one of my plugins, also the successor to Cognitive Subdivision.

Adding one of my plugins

---

res/pluginlist/Jibauni.txt

So sorry. Thanks zuckung for pointing this out.

Fix continuous updates for the Jibauni

---

res/pluginlist/Jibauni.txt

I had to rename the `Jibauni` branch back to `master`.
Reference: https://github.com/TheGiraffe3/Jibauni/discussions/4

Update Jibauni.txt to refix continuous updates

---

res/pluginlist/additional.command.buttons.radial.txt
res/pluginlist/additional.command.buttons.txt
res/pluginlist/real.fluff.txt

changed real.fluff status to deprecated
changed additional.command.buttons status to deprecated
added additional.command.buttons.radial pluginlist file

changed pluginlist files

---

Working/Amalgamation/README.md
Working/Olden Things/README.md
Working/Ultaka Invasion of Milky Way/README.md
res/pluginlist/-Omnis.txt

* Changed the author to be me, because DarcyManoel has decided not to work on Omnis anymore and gave me maintainership. We can remove this change until I contribute a bit more to the plugin if you want.
* Changed the link from the deprecated Adde-Endless-Sky-Mods to EndlessSkyCommunity.
* Cheats was capitalized.

-Omnis list changes

---

res/pluginlist/RW Ships.txt

Per #192, updated the website link to moddb and removed the directlink

Update RW Ships.txt

---

.gitignore
res/errorlog.txt
res/pluginlist/Atlanteans.txt
res/src/makemd.py

added informations to pluginlist file atlanteans.txt
fixed errorlog.txt getting pushed
fixed category "back to top" anchor links linking to wrong md

more fixes

---

res/pluginlist/Jibauni.txt

The plugin no longer adds the Sheragi.

Update Jibauni plug-in's description

---

res/pluginlist/Fire Corporation.txt

Fire Corporation has moved

---

res/pluginlist/Ace Combat Endless Skies.txt
res/pluginlist/Compatibility Plugin.txt
res/pluginlist/Inhibitor Turret Available.txt
res/pluginlist/New Planets.txt
res/pluginlist/es-ui-upgrades.txt
res/pluginlist/variant-outfits.txt

New Plugins Added

---

.github/workflows/on_issue.yml

setting up the issue body as an environment variable and reading that with python script.
#170

issue  body quotation fix

---

res/pluginlist/automata.destruction.0percent.txt
res/pluginlist/automata.in.human.space.txt
res/pluginlist/avgi.licenses.txt
res/pluginlist/better.starts.txt
res/pluginlist/bunrodea.missions.txt
res/pluginlist/captureable.person.ships.txt
res/pluginlist/coalition.shopping.txt
res/pluginlist/disable.person.ships.txt
res/pluginlist/disable.spaceport.repeatables.txt
res/pluginlist/galactic.capital.investment.txt
res/pluginlist/gegno.pirates.txt
res/pluginlist/hai.side.mission.unlocker.txt
res/pluginlist/kestrel.unlocks.txt
res/pluginlist/kor.efret.shipyard.txt
res/pluginlist/mission.helper.txt
res/pluginlist/more.arfectas.txt
res/pluginlist/more.boarding.missions.txt
res/pluginlist/more.person.ships.txt
res/pluginlist/navy.licenses.txt
res/pluginlist/no.more.mereti.mines.txt
res/pluginlist/outfits.weapon.slot.txt
res/pluginlist/paint.your.ships.txt
res/pluginlist/planet.map.txt
res/pluginlist/show.reputation.txt
res/pluginlist/snowfeather.robotics.txt
res/pluginlist/space.fauna.txt
res/pluginlist/too.many.asteroids.txt
res/pluginlist/uniques.txt

added 11 plugins, updated 17 plugin txts

plugin updates

---

res/pluginlist/Louise.Conglomerate.Shipyards.txt

Shorten Louise's Description

---

res/pluginlist/Bunsen.Burner.txt
res/pluginlist/Fundamental.Outfit.Expansion.txt
res/pluginlist/Korunak.Defense.Drones.txt
res/pluginlist/Louise.Conglomerate.Shipyards.txt
res/pluginlist/Solar.Sails.txt

Some description and status updates for Bunsen, FOE, Korunak, Louise and Sails.

Description and status updates

---

.github/workflows/on_issue.yml

This changes the `on_issue` workflow to automatically link the triggering issue. Once you merge a pull request, the issue will be closed.

When a pull request is created, automatically link the issue
